"""
human_review.py
================
Handles the mandatory human-in-the-loop step: ACCEPT / EDIT / REJECT.

The AI never applies a fix automatically. This module only records
what a human decided, so the Dashboard can show real AI<->Human
agreement, and so genuine corrections can be logged for Responsible AI
evidence.

Two lightweight JSON files are used (no database, per project spec):

- human_review/reviews.json
    Every day-to-day review decision (Accept/Edit/Reject) made during
    normal app usage. This is a simple counter/log, NOT a benchmark
    dataset, and must never be conflated with evaluation_results.json.

- responsible_ai/responsible_ai_log.json
    Only genuine human corrections (Edit or Reject with an actual
    corrected diagnosis and reason). The project requires at least 5
    real entries here. Nothing is auto-generated by the AI.
"""

import json
import os
from datetime import datetime, timezone

BASE_DIR = os.path.dirname(__file__)
REVIEWS_DIR = os.path.join(BASE_DIR, "human_review")
REVIEWS_PATH = os.path.join(REVIEWS_DIR, "reviews.json")
RESPONSIBLE_AI_PATH = os.path.join(BASE_DIR, "responsible_ai", "responsible_ai_log.json")

DECISIONS = ("ACCEPT", "EDIT", "REJECT")


def _load_json(path, default):
    if not os.path.exists(path):
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if not content:
                return default
            return json.loads(content)
    except (json.JSONDecodeError, OSError):
        return default


def _save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def load_reviews():
    return _load_json(REVIEWS_PATH, [])


def load_responsible_ai_log():
    return _load_json(RESPONSIBLE_AI_PATH, [])


def record_review(case_ref: str, decision: str, ai_diagnosis: dict,
                   correction: str = None, reason: str = None,
                   evidence: str = None):
    """
    Record a single human review decision made during normal
    troubleshooting use (not benchmark evaluation).

    decision must be one of ACCEPT / EDIT / REJECT.

    If decision is EDIT or REJECT and both `correction` and `reason`
    are provided (i.e. this is a genuine, specific correction rather
    than a blank rejection), it is ALSO appended to the Responsible AI
    log.
    """
    decision = (decision or "").upper()
    if decision not in DECISIONS:
        raise ValueError(f"decision must be one of {DECISIONS}, got {decision!r}")

    reviews = load_reviews()
    entry = {
        "case_ref": case_ref,
        "decision": decision,
        "ai_root_cause": (ai_diagnosis or {}).get("root_cause"),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    reviews.append(entry)
    _save_json(REVIEWS_PATH, reviews)

    logged_correction = False
    if decision in ("EDIT", "REJECT") and correction and reason:
        _append_responsible_ai_entry(
            case_id=case_ref,
            ai_diagnosis=(ai_diagnosis or {}).get("root_cause", ""),
            human_correction=correction,
            reason=reason,
            evidence=evidence or "",
        )
        logged_correction = True

    return entry, logged_correction


def _append_responsible_ai_entry(case_id, ai_diagnosis, human_correction, reason, evidence):
    log = load_responsible_ai_log()
    log.append({
        "case_id": case_id,
        "ai_diagnosis": ai_diagnosis,
        "human_correction": human_correction,
        "reason": reason,
        "evidence": evidence,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })
    _save_json(RESPONSIBLE_AI_PATH, log)


def review_summary():
    """
    Returns counts of Accepted / Edited / Rejected and, if there is at
    least one review, the AI<->Human agreement percentage
    (ACCEPT counted as agreement).
    """
    reviews = load_reviews()
    counts = {"ACCEPT": 0, "EDIT": 0, "REJECT": 0}
    for r in reviews:
        d = r.get("decision")
        if d in counts:
            counts[d] += 1

    total = sum(counts.values())
    agreement = None
    if total > 0:
        agreement = round(counts["ACCEPT"] / total * 100, 1)

    return {
        "accepted": counts["ACCEPT"],
        "edited": counts["EDIT"],
        "rejected": counts["REJECT"],
        "total_reviews": total,
        "ai_human_agreement_pct": agreement,
    }
